### ISSUE TITLE
Hi, Keith! I can't loggin to server with my account

### ISSUE THREAD

**Issue by imanalopher** [Tracman-org/Server#124]
Mine is iman.mamadiyev@gmail.com
and can't loggin in android

**Comment by keith24** [comment]
I see your account was been created on March 17, but there's no password in the database.  Did you receive a link by email to create a password?  Did you try to create one?  

That link should be expired by now, but you can get another password reset link using the [reset password page](https://www.tracman.org/login/forgot).  

Let me know how that goes.
